"""
Django settings for ERtimes project.

Generated by 'django-admin startproject' using Django 1.8.2.

For more information on this file, see
https://docs.djangoproject.com/en/1.8/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/1.8/ref/settings/
"""

# Build paths inside the project like this: os.path.join(BASE_DIR, ...)
import os

REAL_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
BASE_DIR = os.path.abspath(os.path.join(REAL_ROOT, os.pardir))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/1.8/howto/deployment/checklist/

SECRET_KEY = '4+6u*@0qw3s+d)x$ev8^^a^e%q4=w$npw!0o=h^_g3ljn^9-@7'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

SITE_ID = 1


# Application definition

DJANGO_APPS = (
    'django.contrib.admin',
    'django.contrib.sites',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'pure_pagination',
)

THIRD_PARTY_APPS = (
    'cities_light',
    'rest_framework',
)


PROJECT_APPS = (
    'apps.accounts',
    'apps.dashboard',
    'apps.profile',
    'tests',
    'apps.leadquote',
)
INSTALLED_APPS = DJANGO_APPS+THIRD_PARTY_APPS+PROJECT_APPS

MIDDLEWARE_CLASSES = (
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.auth.middleware.SessionAuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    'django.middleware.security.SecurityMiddleware',
)

ROOT_URLCONF = 'quick_quote.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, "templates")],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'quick_quote.wsgi.application'


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/1.8/howto/static-files/

STATIC_URL = '/static/'
STATIC_ROOT = os.path.join(BASE_DIR, "static")
MEDIA_URL = '/media/'
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

STATICFILES_FINDERS = (
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder',
)

STATICFILES_DIRS = (

    os.path.join(BASE_DIR, 'staticfiles'),
)

# Database
# https://docs.djangoproject.com/en/1.8/ref/settings/#databases

"""
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql_psycopg2',
        'NAME': "temp_quick_quote",
        'USER': "postgres",
        'PASSWORD': "qwerty",
        'PORT': '5432',
        'HOST': 'localhost',
        'STORAGE_ENGINE': 'MYISAM',
    }
}
"""

# navi 
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': os.path.join(BASE_DIR, 'db.sqlite3'),
    }
}

AUTH_USER_MODEL = 'accounts.User'

PAGINATION_SETTINGS = {
    'PAGE_RANGE_DISPLAYED': 4,
    'MARGIN_PAGES_DISPLAYED': 2,

    'SHOW_FIRST_PAGE_WHEN_INVALID': True,
}


EMAIL_USE_TLS = True
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_HOST_USER = 'quickquote@learlabs.com'
EMAIL_HOST_PASSWORD = 'learlight'
EMAIL_PORT = 587
DEFAULT_FROM_EMAIL = 'Jewelers Mutual <quickquote@learlabs.com>'

EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'

LOGIN_URL = '/'

RECAPTCHA_PUBLIC_KEY = '6LfBzg8TAAAAAOkYZ5DHWazQVxdn4dWp3OddKjO3'
RECAPTCHA_PRIVATE_KEY = '6LfBzg8TAAAAAEWnFKvaQOI9KLmuvaeij7UKOex4'

AUTHENTICATION_BACKENDS = ('django.contrib.auth.backends.ModelBackend',
                           'apps.accounts.backends.EmailAuthBackend',
                           )
LOGIN_REDIRECT_URL = '/dashboard/associate/'

CITIES_LIGHT_TRANSLATION_LANGUAGES = ['en']


